### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by fresm** [pmezard/osm#1]
Bonjour Patrick,

what about adding an intro to your o5m manipulation tool?

Can I use the print{xml}nodes command in conjunction with Overpass?

**Comment by pmezard** [comment]
Fixed, thank you for the reminder, it has been on my list for more than a year.

I do not really know what you can do with `print{xml}nodes` commands. AFAIK, I wrote it to validate the o5m reader by roundtripping and comparing with reference osm files.
